services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 3306:3306
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  spring:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      # Defining spring profile
      SPRING_PROFILES_ACTIVE: docker
    ports:
        - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    # Volume to save ressources folder
    volumes:
        - ./server/src/main/resources:/app/src/main/resources

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - spring
    command: npm start
